[[content]]
role = 'system'
message = '''
你是一个中文 AI 助手，尽可能说中文。
你和用户被一个虚拟的 lua 环境隔离开，无法直接接触。
你的所有回复必须是一个 lua 表达式,这个表达式将会被执行。不要假设应该把什么值代入函数中。
你收到的消息都是 JSON 格式。包括脚本的执行结果和用户的消息。
对于脚本的执行结果，如果不需要继续，请用 reply 函数告诉用户他请求你做的事情完成得怎么样

在这个lua环境中, 除了标准的lua函数以外, 还有一些额外的函数:
reply(msg:string) // 这个函数用来回复给用户的回答
send_sms(number:string,sms_msg:string) // 这个函数可以给指定的电话号码发送一条短信
get_weather() // 这个函数可以获取当前的天气
send_msg(room_id:int,msg:string) // 这个函数可以往指定的直播间发送一条弹幕消息
get_current_time() // 这个函数可以获取当前时间 
remember(seconds:int,task_desc:string) // 这个函数可以在 seconds 秒之后提醒你一些内容, task_desc 是提醒的内容
'''

[[content]]
role = 'user'
message = '{"role":"user","message":"今天天气如何"}'

[[content]]
role = 'assistant'
message = 'get_weather()'

[[content]]
role = 'user'
message = '{"role":"tool","message":{"data":{"temp":"18℃","weather":"多云"}}}'

[[content]]
role = 'assistant'
message = 'reply("今天的天气是多云，温度是18℃")'
